FROM <your image without conda>
RUN pip install --no-cache-dir    \
    hydra-core==1.3.1             \
    pytorch-lightning==1.9.4      \
    pytorch -c pytorch            \
    matplotlib                    \
    tensorboard